version: '3.8'

services:

# Data bases
    mongo-db:
        image: mongo:latest
        restart: always
        hostname: mongo-db
        container_name: fiware-mongo
        ports:
            - "27017:27017"
        volumes:
            - db-data:/data/db

# Orion is the context broker
    orion:
        image: letsfiware/orion:3.10.1
        restart: always
        hostname: orion
        container_name: fiware-orion
        depends_on:
            - mongo-db
        ports:
            - "1026:1026"
        command: -dbhost mongo-db -corsOrigin __ALL -corsMaxAge 600

# Persistent Data
    fiware-sth-comet:
        image: letsfiware/sth-comet:2.10.0
        restart: always
        hostname: sth-comet
        container_name: fiware-sth-comet
        depends_on:
            - mongo-db
        ports:
            - "8666:8666"
        environment:
            - STH_HOST=0.0.0.0
            - STH_PORT=8666
            - DB_PREFIX=sth_
            - DB_URI=mongo-db:27017
            - LOGOPS_LEVEL=DEBUG

# MQTT Broker
    mosquitto:
        image: eclipse-mosquitto:latest
        restart: always
        hostname: mosquitto
        container_name: fiware-mosquitto
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

# MQTT Broker to NGSI
    iot-agent:
        image: letsfiware/iotagent-ul:2.4.2
        restart: always
        hostname: iot-agent
        container_name: fiware-iot-agent
        depends_on:
            - mongo-db
            - mosquitto
        expose:
            - "4041"
        ports:
            - "4041:4041"
        environment:
            - IOTA_CB_HOST=orion
            - IOTA_CB_PORT=1026
            - IOTA_NORTH_PORT=4041
            - IOTA_REGISTRY_TYPE=mongodb
            - IOTA_LOG_LEVEL=DEBUG
            - IOTA_TIMESTAMP=true
            - IOTA_CB_NGSI_VERSION=v2
            - IOTA_AUTOCAST=true
            - IOTA_MONGO_HOST=mongo-db
            - IOTA_MONGO_PORT=27017
            - IOTA_MONGO_DB=iotagentul
            - IOTA_PROVIDER_URL=http://iot-agent:4041
            - IOTA_MQTT_HOST=mosquitto
            - IOTA_MQTT_PORT=1883

# Azure SQL Edge
    sqlserver:
        image: mcr.microsoft.com/azure-sql-edge:latest
        restart: always
        environment:
            SA_PASSWORD: "senha" # Username is 'SA'
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        expose:
            - "1433"
        ports:
            - "1433:1433"
        volumes:
            - sqlserver:/var/opt/mssql

volumes:
    db-data:
    sqlserver:
