version: '3.8'

services:
  # Data bases
  mongo-db:
    image: mongo:7.0.9
    restart: always
    hostname: mongo-db
    container_name: fiware-mongo
    expose:
      - "27017"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PWD}
        
  # Orion is the context broker
  orion:
    image: letsfiware/orion:3.10.1
    restart: always
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    expose:
      - "1026"
    ports:
      - "${ORION_PORT}:1026"
    command: -dbhost mongo-db -corsOrigin __ALL -corsMaxAge 600 -dbuser $MONGO_USER -dbpwd $MONGO_PWD

  # Persistent Data
  sth-comet:
    image: letsfiware/sth-comet:2.10.0
    restart: always
    hostname: sth-comet
    container_name: fiware-sth-comet
    depends_on:
      - mongo-db
    expose:
      - "8666"
    ports:
      - "${STH_COMET_PORT}:8666"
    environment:
      - STH_HOST=0.0.0.0
      - STH_PORT=8666
      - DB_PREFIX=sth_comet
      - DB_USERNAME=${MONGO_USER}
      - DB_PASSWORD=${MONGO_PWD}
      - DB_URI=mongo-db:27017
      - LOGOPS_LEVEL=DEBUG

  # MQTT Broker
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    hostname: mosquitto
    container_name: fiware-mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "${MOSQUITTO_PORT_1}:1883"
      - "${MOSQUITTO_PORT_2}:9001"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  # MQTT Broker to NGSI
  iot-agent:
    image: letsfiware/iotagent-ul:2.4.2
    restart: always
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongo-db
      - mosquitto
    expose:
      - "4041"
    ports:
      - "${IOT_AGENT_PORT}:4041"
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongo-db
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagent-ul?authSource=admin
      - IOTA_MONGO_USER=${MONGO_USER}
      - IOTA_MONGO_PASSWORD=${MONGO_PWD}
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883

  # Azure SQL Edge
  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: always
    hostname: mssql
    environment:
      - SA_PASSWORD=${MSSQL_PWD}
      - ACCEPT_EULA=1
      - MSSQL_PID=Developer
    expose:
      - "1433"
    ports:
      - "${MSSQL_PORT}:1433"
    volumes:
      - mssql:/var/opt/mssql

volumes:
  db-data:
  mssql:
